- name: add key for redis
  apt_key:
    url: https://packages.redis.io/gpg
    keyring: /usr/share/keyrings/redis-archive-keyring.gpg

- name: redis repo
  apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/redis-archive-keyring.gpg] https://packages.redis.io/deb focal main 
    filename: redis  

- name: install redis
  apt: name=redis

- name: configure persstence
  shell: echo "{{item}}" | redis-cli  
  loop:
    - config set save ''
    - config set appendonly yes
    - config set appendfsync always
    - config set requirepass myverystrongpassword
    - config rewrite 
