- name: add mongodb repository key
  apt_key: >-
    url=https://www.mongodb.org/static/pgp/server-4.2.asc
    state=present

- name: add mongodb repository
  copy: src=mongodb.list dest=/etc/apt/sources.list.d/ backup=yes

- name: install mongodb server
  apt: name=mongodb-server

- name: create admin user before turning on security
  community.mongodb.mongodb_user:
    database: admin
    name: admin
    password: admin
    roles: readWrite,dbAdmin,userAdmin,root
    state: present
  ignore_errors: yes
  
- name: mongo config
  template:
    src: mongodb.conf.j2
    dest: /etc/mongodb.conf
    owner: mongodb
    group: mongodb
    mode: '0640'
  notify: restart mongodb

- name: copy backup script
  copy:
    src: bkp_mongo.sh
    dest: /tmp/

- name: create mongo backup
  script: /tmp/bkp_mongo.sh
  when: mongodb_createbkp

