- name: create users
  command: rabbitmqctl list_users
  register: vusers


- name: create users
  shell: |
    rabbitmqctl add_user {{item}} {{item}}
    rabbitmqctl set_permissions -p {{item}} {{item}}   "." "." "."
  when:  vusers.stdout is not search(item)
  with_items:
    - "{{ rmq_users }}"

